version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8u162-jdk
    working_directory: ~/Tjanseauktion
    steps:
      - checkout
      - restore_cache:
          key: tjanser-java-spring-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: tjanser-java-spring-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar
